#!/bin/bash -e
for i in examples/*; do
  printf "$i..."

  if [[ $i == *"include-"* ]]; then
    mocha --require . examples/helper.js $i > /dev/null
    ecode=$?
  else
    if [[ $i == *"babel-"* ]]; then
      mocha --require babel-register --require . $i > /dev/null
      ecode=$?
    else
      mocha --include examples/helper.js --require . $i > /dev/null
      ecode=$?
    fi
  fi

  if [[ $i == *"failing"* ]] || [[ $i == *"explosive"* ]] ||
      [[ $i == *"explode"* ]] || [[ $i == *"rejects-promise"* ]]; then
    if [[ $ecode == 0 ]]; then
      echo "Failure: $i"
      echo "Expected exitcode != 0, but saw $ecode"
      exit 1
    fi
  else
    if [[ $ecode != 0 ]]; then
      echo "Failure: $i"
      echo "Expected exitcode == 0, but saw $ecode"
      exit 1
    fi
  fi
  printf " ok\n"
done
