#!/bin/bash
set -uo pipefail
IFS=$'\n\t'
for i in examples/*; do
  printf "$i..."

  if [[ $i == *"promise"* ]]; then
    mocha --include examples/helper-promises.js --require . $i > /dev/null
    ecode=$?
  else
    if [[ $i == *"babel-"* ]]; then
      mocha --require babel-register --require . $i > /dev/null
      ecode=$?
    else
      if [[ $i != *"helper"* ]]; then
        mocha --include examples/helper.js --require . $i > /dev/null
        ecode=$?
      else
        printf " skip helper\n"
        continue;
      fi
    fi
  fi

  if [[ $i == *"failing"* ]] || [[ $i == *"explode"* ]] || [[ $i == *"throws"* ]]; then
    if [[ $ecode == 0 ]]; then
      echo "Failure: $i"
      echo "Expected exitcode != 0, but saw $ecode"
      exit 1
    fi
  else
    if [[ $ecode != 0 ]]; then
      echo "Failure: $i"
      echo "Expected exitcode == 0, but saw $ecode"
      exit 1
    fi
  fi
  printf " ok\n"
done
